# -*- coding: utf-8 -*-
"""N-Gram Models & Unigram Probability

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wD6L5wYkyrdL8o06mG62-foRElm67vh0
"""

# ============================================================
#   NLP Assignment: N-Gram Models & Unigram Probability
# ============================================================

# ──────────────────────────────────────────────────────────
# SECTION 1 — Filtering Stopwords using Regex & Bigrams
# ──────────────────────────────────────────────────────────

import re
from collections import defaultdict, Counter
import math

# ---------- Task 1 ----------
print("=" * 55)
print("SECTION 1: Stopword Removal & Bigram Generation")
print("=" * 55)

sentence   = "I am learning NLP because NLP is fascinating and useful."
stopwords  = ["I", "am", "is", "and", "the", "because"]

# Build a regex pattern:  \b(word1|word2|...)\b  — whole-word, case-sensitive
pattern = r'\b(' + '|'.join(re.escape(w) for w in stopwords) + r')\b'
print(f"\nRegex pattern  : {pattern}")

# Remove stopwords, then strip leftover punctuation & extra spaces
cleaned = re.sub(pattern, '', sentence)          # remove stopwords
cleaned = re.sub(r'[^\w\s]', '', cleaned)        # remove punctuation
cleaned = re.sub(r'\s+', ' ', cleaned).strip()   # collapse whitespace

print(f"Original text  : {sentence}")
print(f"Cleaned text   : {cleaned}")

# Tokenise and generate bigrams
tokens = cleaned.split()
print(f"\nTokens         : {tokens}")

bigrams = [(tokens[i], tokens[i+1]) for i in range(len(tokens) - 1)]
print(f"\nBigrams (after stopword removal):")
for bg in bigrams:
    print(f"  {bg}")


# ──────────────────────────────────────────────────────────
# SECTION 2 — Bigram Probabilities using Regex & MLE
# ──────────────────────────────────────────────────────────

print("\n" + "=" * 55)
print("SECTION 2: Bigram Probabilities & MLE")
print("=" * 55)

corpus = "machine learning is amazing. deep learning is powerful. learning is continuous."

# Normalise: lowercase, remove punctuation, split into tokens
corpus_clean  = re.sub(r'[^\w\s]', '', corpus.lower())
corpus_tokens = corpus_clean.split()
print(f"\nCorpus tokens  : {corpus_tokens}")

# Count unigrams and bigrams
unigram_counts = Counter(corpus_tokens)
bigram_counts  = Counter(
    (corpus_tokens[i], corpus_tokens[i+1])
    for i in range(len(corpus_tokens) - 1)
)

print(f"\nUnigram counts : {dict(unigram_counts)}")
print(f"\nBigram counts  : {dict(bigram_counts)}")

# MLE: P(w2 | w1) = count(w1, w2) / count(w1)
target_bigram = ("learning", "is")
bigram_count  = bigram_counts[target_bigram]
unigram_count = unigram_counts[target_bigram[0]]
mle_prob      = bigram_count / unigram_count

print(f"\nTarget bigram  : '{' '.join(target_bigram)}'")
print(f"  Count(learning, is) = {bigram_count}")
print(f"  Count(learning)     = {unigram_count}")
print(f"  MLE P(is|learning)  = {bigram_count}/{unigram_count} = {mle_prob:.4f}")


# ──────────────────────────────────────────────────────────
# SECTION 3 — N-Gram Model with Laplace (Add-One) Smoothing
# ──────────────────────────────────────────────────────────

print("\n" + "=" * 55)
print("SECTION 3: N-Gram Model with Laplace Smoothing")
print("=" * 55)

def build_ngram_model(corpus: str, n: int) -> dict:
    """
    Build an N-gram language model with Laplace (Add-One) smoothing.

    Parameters
    ----------
    corpus : str  — raw input text
    n      : int  — order of the n-gram (e.g. 2 = bigram)

    Returns
    -------
    dict — {(w1,...,w_{n-1}): {next_word: smoothed_probability}}
    """
    text   = re.sub(r'[^\w\s]', '', corpus.lower())
    tokens = text.split()
    V      = len(set(tokens))          # vocabulary size

    context_counts = defaultdict(int)
    ngram_counts   = defaultdict(int)

    for i in range(len(tokens) - n + 1):
        ngram   = tuple(tokens[i : i + n])
        context = ngram[:-1]
        context_counts[context] += 1
        ngram_counts[ngram]     += 1

    # Laplace smoothing: P(w|ctx) = (count(ctx,w)+1) / (count(ctx)+V)
    model = defaultdict(dict)
    for ngram, cnt in ngram_counts.items():
        context   = ngram[:-1]
        next_word = ngram[-1]
        model[context][next_word] = round(
            (cnt + 1) / (context_counts[context] + V), 6
        )

    return dict(model)


text = "I love NLP and I love machine learning"
for n in [2, 3]:
    model = build_ngram_model(text, n)
    label = "Bigram" if n == 2 else "Trigram"
    print(f"\n{label} model (n={n}):")
    for ctx, probs in model.items():
        print(f"  Context {ctx}:")
        for word, prob in probs.items():
            print(f"    P({word!r:<12} | {ctx}) = {prob:.6f}")


# ──────────────────────────────────────────────────────────
# SECTION 4 — Perplexity Calculation
# ──────────────────────────────────────────────────────────

print("\n" + "=" * 55)
print("SECTION 4: Perplexity Calculation")
print("=" * 55)

def compute_perplexity(train_corpus: str, test_sentence: str, n: int = 2) -> float:
    """
    Compute perplexity of a test sentence under an n-gram model
    trained on train_corpus, with Laplace smoothing.

    Perplexity = exp( -1/N * sum( log P(w_i | context) ) )
    """
    model       = build_ngram_model(train_corpus, n)
    train_clean = re.sub(r'[^\w\s]', '', train_corpus.lower()).split()
    V           = len(set(train_clean))

    test_tokens = re.sub(r'[^\w\s]', '', test_sentence.lower()).split()

    if len(test_tokens) < n:
        raise ValueError(f"Test sentence too short for n={n}.")

    log_prob_sum = 0.0
    num_ngrams   = 0

    for i in range(len(test_tokens) - n + 1):
        ngram   = tuple(test_tokens[i : i + n])
        context = ngram[:-1]
        word    = ngram[-1]

        if context in model and word in model[context]:
            prob = model[context][word]
        else:
            # Unseen context → uniform Laplace-smoothed fallback
            prob = 1 / V

        log_prob_sum += math.log(prob)
        num_ngrams   += 1
        print(f"  P({word!r:<10} | {context}) = {prob:.6f}  →  log = {math.log(prob):.4f}")

    perplexity = math.exp(-log_prob_sum / num_ngrams)
    return perplexity


train_corpus  = "I love NLP and I love machine learning"
test_sentence = "I love NLP models"

print(f"\nTrain corpus   : \"{train_corpus}\"")
print(f"Test sentence  : \"{test_sentence}\"")
print(f"\nStep-by-step bigram probabilities:")

pp = compute_perplexity(train_corpus, test_sentence, n=2)
print(f"\nPerplexity     : {pp:.4f}")
print("(Lower perplexity → model finds the test sentence more probable)")

